routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/bKategori/{id}', 'HomeController@bKategori')->name('bKategori');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('kategori', 'KategoriController');
    Route::get('getKategori','KategoriController@getKategori');
    Route::resource('produk', 'ProdukController');
    Route::get('getProduk','ProdukController@getProduk');
    Route::get('lihatProduk/{id}','ProdukController@lihatProduk');
    Route::get('lihatBerdasarkanKategori/{id}','ProdukController@lihatBerdasarkanKategori');
});

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ProdukModel;
use App\KategoriModel;
use DataTables;
use Image;
use DB;
use Illuminate\Support\Str;
use File;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = KategoriModel::select(['id','nama'])->get();
        return view('admin.produk.index',['kategori' => $kategori]);
    }
    public function lihatBerdasarkanKategori($id)
    {
    $kategoris = KategoriModel::select(['id','nama'])->get();
    $kategori = ProdukModel::whereHas('kategori', function($q) use ($id){

        $q->where('kategori.id', '=',$id);
    })->get();        
    return view('admin.produk.lihatBerdasarkanKategori',['kategori' => $kategori,
    'kategoris' => $kategoris]);
    }
    public function getProduk()
    {
        $getProduk = ProdukModel::select(['id', 'nama']);

        return Datatables::of($getProduk)
            ->addColumn('action', function ($produk) {
                return '<button type="button" id="deleteProduk" class="btn btn-xs btn-danger" data-id="'.$produk->id.'">Delete</button>
                <a href="produk/'.$produk->id.'/edit" class="btn btn-xs btn-primary">Edit</a>
                <a href="lihatProduk/'.$produk->id.'/" class="btn btn-xs btn-info">Lihat Produk</a>';
            })
            ->make(true);
    }
    public function lihatProduk($id)
    {
        $produk = ProdukModel::findOrFail($id);
        return view('admin.produk.lihatProduk',['produk' => $produk]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = KategoriModel::select(['id','nama'])->get();
        return view('admin.produk.create', ['kategori' => $kategori]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {        
        if($request->hasFile('foto'))
        {
            $originalImage = $request->file('foto');
            //Get Filename with The Extension
            $filenameWithExt = $request->file('foto')->getClientOriginalName();

            //Get Just Filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            
            //Get Just Ext
            $extension = $request->file('foto')->getClientOriginalExtension();

            $slugNamaProduk = Str::slug($request->input('nama'), '_');
            //Filename to Store
            $filenameToStore = $slugNamaProduk.'_'.str_random(8).'.'.$extension;
            
            $thumbnailImage = Image::make($originalImage);            
            $originalPath = public_path().'/fotoProduk/';
            $thumbnailImage->save($originalPath.$filenameToStore);

            $produk = new ProdukModel;
            $produk->nama = $request->input('nama');
            $produk->foto = $filenameToStore;
            $produk->deskripsi = $request->input('deskripsi');
            $produk->save();
            
            $produk->kategori()->sync($request->kategori, false);
            return redirect('produk');
        } else {
            $produk = new ProdukModel;
            $produk->nama = $request->input('nama');
            $produk->foto = 'default_image.jpg';
            $produk->deskripsi = $request->input('deskripsi');
            $produk->save();
            $produk->kategori()->sync($request->kategori, false);
            return redirect('produk');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $produk = ProdukModel::findOrFail($id);
        return response()->json($produk,200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produk = ProdukModel::findOrFail($id);
        $getKategoriId = DB::table('produk_kategori')->where('produk_id','=',$id)->pluck('kategori_id')->all();
        $kategori = KategoriModel::all();
        return view('admin.produk.edit',[
            'produk' => $produk,
            'kategori'=> $kategori,
            'getKategoriId' => $getKategoriId
        ]);
    }    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->hasFile('foto'))
        {
            $originalImage = $request->file('foto');
            //Get Filename with The Extension
            $filenameWithExt = $request->file('foto')->getClientOriginalName();

            //Get Just Filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            
            //Get Just Ext
            $extension = $request->file('foto')->getClientOriginalExtension();

            $slugNamaProduk = Str::slug($request->input('nama'), '_');
            //Filename to Store
            $filenameToStore = $slugNamaProduk.'_'.str_random(8).'.'.$extension;
            
            $thumbnailImage = Image::make($originalImage);            
            $originalPath = public_path().'/fotoProduk/';
            $thumbnailImage->save($originalPath.$filenameToStore);

            $produk = ProdukModel::findOrFail($id);
            $deleteFoto = public_path().'/fotoProduk/'.$produk->foto;
            File::delete($deleteFoto);
            $produk->nama = $request->input('nama');
            $produk->foto = $filenameToStore;
            $produk->deskripsi = $request->input('deskripsi');
            $produk->save();
            
            if (isset($request->kategori)) {
                $produk->kategori()->sync($request->kategori);
            } else {
                $produk->kategori()->sync(array());
            }
            return redirect('produk');
        } else {
            $produk = ProdukModel::findOrFail($id);
            $produk->nama = $request->input('nama');            
            $produk->deskripsi = $request->input('deskripsi');
            $produk->save();
            if (isset($request->kategori)) {
                $produk->kategori()->sync($request->kategori);
            } else {
                $produk->kategori()->sync(array());
            }
            return redirect('produk');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produk = ProdukModel::findOrFail($id);
        $deleteFoto = public_path().'/fotoProduk/'.$produk->foto;
        File::delete($deleteFoto);
        $produk->kategori()->wherePivot('produk_id','=',$id)->detach();
        $produk->delete();

    }
}

resources/views/admin/produk/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  <form action="{{ route('produk.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Nama</label>
                      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Masukan Nama Produk" name="nama">
                    </div>
                    @foreach ($kategori as $item)
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="checkbox" name="kategori[]" id="inlineCheckbox{{$item->id}}" value="{{ $item->id }}">
                      <label class="form-check-label" for="inlineCheckbox{{$item->id}}">{{ $item->nama }}</label>
                    </div>                        
                    @endforeach
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Foto</label>
                      <input type="file" class="form-control" name="foto">
                    </div>
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Deskripsi</label>
                      <textarea name="deskripsi" id="deskripsi" cols="30" rows="10" class="form-control"></textarea>
                    </div>                    
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/produk/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form action="{{ url('produk/'.$produk->id) }}" method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    {{ csrf_field() }}
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Nama</label>
                      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Masukan Nama Produk" name="nama" value="{{ $produk->nama }}">
                      <input type="hidden" name="id" value="{{$produk->id}}">
                    </div>
                      @foreach ($kategori as $items)
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="kategori[]" id="inlineCheckbox{{$items->id}}" value="{{ $items->id }}" {{ in_array($items->id,$getKategoriId) ? 'checked' : '' }}>
                        <label class="form-check-label" for="inlineCheckbox{{$items->id}}">{{ $items->nama }}</label>
                      </div>                              
                      @endforeach                                          
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Foto</label>
                      <input type="file" class="form-control" name="foto" value="{{$produk->foto}}">
                    </div>
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Deskripsi</label>
                      <textarea name="deskripsi" id="deskripsi" cols="30" rows="10" class="form-control">{{$produk->deskripsi}}</textarea>
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/produk/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="card">
    <div class="card-header">
      Daftar Produk
    </div>
    <div class="card-body">
      <a href="{{ url('produk/create') }}" class="btn btn-info" style="margin-bottom:20px;">Tambah Data</a>
      @foreach ($kategori as $item)
        <a href="{{ url('lihatBerdasarkanKategori/'.$item->id) }}" class="btn btn-secondary" style="margin-bottom:20px;">{{$item->nama}}</a>          
      @endforeach
      <div class="table-responsive">
        <table class="table" id="produk-table" width="100%">
          <thead>
            <tr>
              <td>ID</td>
              <td>Nama</td>
              <td>Actions</td>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td>ID</td>
              <td>Nama</td>
              <td>Actions</td>
            </tr>
          </tfoot>          
        </table>
      </div>
    </div>
  </div>
</div>
<div class="modal fade bd-example-modal-lg" id="deleteProdukModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="id" id="id">
        <div class="infoText">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" data-idDel="" type="button" id="deleteProduk">Delete</button>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/produk/lihatBerdasarkanKategori.blade.php
@extends('layouts.app')
@section('kategori')
  @foreach ($kategoris as $items)
    <a class="dropdown-item" href="{{ url('bKategori/'.$items->id) }}">{{$items->nama}}</a>      
  @endforeach
@endsection
@section('content')
  <div class="container">    
    <div class="card">
      @foreach($kategori as $item)
        <div class="card-header">        
            {{ $item->nama }}
        </div>
      <div class="card-body">
          <img class="card-img-top" src="{{ asset('fotoProduk/'.$item->foto)}}" alt="Card image cap">        
        {{ $item->deskripsi }}          
      </div>  
      @endforeach 
    </div>
    
  </div>
  
@endsection

resources/views/admin/produk/lihatProduk.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
      <div class="card">
        <div class="card-header">
          <h3>{{$produk->nama}}</h3>
        </div>
        <img class="card-img-top" src="{{ asset('fotoProduk/'.$produk->foto)}}" alt="Card image cap">
        <div class="card-body">
          <p class="card-text">{{$produk->deskripsi}}</p>
          Kategori : 
          @foreach ($produk->kategori as $item)

              {{ $item->nama }}
              
          @endforeach
          <br>
          <a href="{{ url('produk') }}">Kembali</a>

        </div>
      </div>
    </div>
@endsection