routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/bKategori/{id}', 'HomeController@bKategori')->name('bKategori');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('kategori', 'KategoriController');
    Route::get('getKategori','KategoriController@getKategori');
    Route::resource('produk', 'ProdukController');
    Route::get('getProduk','ProdukController@getProduk');
    Route::get('lihatProduk/{id}','ProdukController@lihatProduk');
    Route::get('lihatBerdasarkanKategori/{id}','ProdukController@lihatBerdasarkanKategori');
});

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\KategoriModel;
use DataTables;
class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.kategori.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $kategori = new KategoriModel;
        $kategori->nama = $request->input('nama');
        $kategori->save();
        return redirect('kategori');
    }
    public function getKategori()
    {
        $getKategori = KategoriModel::select(['id', 'nama']);

        return Datatables::of($getKategori)
            ->addColumn('action', function ($kategori) {
                return '<button type="button" id="deleteKategori" class="btn btn-xs btn-danger" data-id="'.$kategori->id.'">Delete</button>
                <a href="kategori/'.$kategori->id.'/edit" class="btn btn-xs btn-primary">Edit</a>';
            })
            ->make(true);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kategori = KategoriModel::findOrFail($id);
        return response()->json($kategori,200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = KategoriModel::findOrFail($id);
        return view('admin.kategori.edit',['kategori' => $kategori]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kategori = KategoriModel::findOrFail($id);
        $kategori->nama = $request->input('nama');
        $kategori->save();
        return redirect('kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = KategoriModel::findOrFail($id);
        $kategori->delete();
    }
}

resources/views/admin/kategori/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  <form action="{{ route('kategori.store') }}" method="POST">
                        @csrf
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Nama</label>
                      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Masukan nama Kategori" name="nama">
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/kategori/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  <form action="{{ url('kategori/'.$kategori->id) }}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                      <label for="exampleFormControlInput1">Nama</label>
                      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Masukan nama Kategori" name="nama" value="{{$kategori->nama}}">
                      <input type="hidden" name="id" value="{{$kategori->id}}">
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/kategori/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="card">
    <div class="card-header">
      Daftar Kategori
    </div>
    <div class="card-body">
      <a href="{{ url('kategori/create') }}" class="btn btn-info" style="margin-bottom:20px;">Tambah Data</a>
      <div class="table-responsive">
        <table class="table" id="kategori-table" width="100%">
          <thead>
            <tr>
              <td>ID</td>
              <td>Nama</td>
              <td>Actions</td>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td>ID</td>
              <td>Nama</td>
              <td>Actions</td>
            </tr>
          </tfoot>          
        </table>
      </div>
    </div>
  </div>
</div>
<div class="modal fade bd-example-modal-lg" id="deleteKategoriModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="id" id="id">
        <div class="infoText">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" data-idDel="" type="button" id="deleteKategori">Delete</button>
      </div>
    </div>
  </div>
</div>
@endsection